# Generated by Django 4.2.11 on 2024-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmate', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='business',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
