# Generated by Django 4.2.11 on 2024-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmate', '0005_product_price_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
